
version: "3"
services:
  php:
    # імʼя контейнеру, яке будемо використовувати при вході на контейнер
    container_name: php_pro_kent17
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./
      # посилання на докерфайл з налаштуванням контейнеру
      dockerfile: "docker/configs/php/Dockerfile"
    #            extra_hosts:
    #                - "host.docker.internal:host-gateway"
    # встановлюємо змінні оточення
    environment:
      XDEBUG_CONFIG: "remote_host=127.0.0.1"
      PHP_IDE_CONFIG: "serverName=docker"
    # прописуємо синхронізацію директорій
    volumes:
      - ./:/srv/src/php_pro_kent
    links:
       -   db_mysql

  db_mysql:
    image: mysql:latest
    container_name: php_pro_3_mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: php_pro
      MYSQL_USER: kent
      MYSQL_PASSWORD: 1111

  nginx:
    image: nginx:latest
    container_name: php_pro_3_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/srv/src/php_pro_2
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    links:
      - php

